FROM debian:stretch-slim

RUN apt-get update
RUN apt-get install -y apt-transport-https \
		    ca-certificates \
		    wget
		    
RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
RUN echo "deb https://packages.sury.org/php/ stretch main" > /etc/apt/sources.list.d/php.list

RUN apt-get update
RUN apt-get install -y php7.1-cli php7.1-fpm
RUN sed -ie 's/^listen = /;&/' /etc/php/7.1/fpm/pool.d/www.conf
RUN echo listen = $(awk 'END{print $1}' /etc/hosts) >> /etc/php/7.1/fpm/pool.d/www.conf
RUN echo listen = 9000 >> /etc/php/7.1/fpm/pool.d/www.conf

VOLUME nginx-html1:/var/www/html:rw

COPY entrypoints/entry-php.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

EXPOSE 9000
